### ISSUE TITLE
试了一下，匹配的正确率很低啊~

### ISSUE THREAD

**Issue by hyywestwood** [oscarcx123/afk-arena-tools#1]
尝试了一下王者之塔模式，选关阶段的“挑战”一直匹配率很低。。。
可能跟对应手机屏幕的大小或分辨率有关？

**Comment by hyywestwood** [comment]
但还是要赞一个

**Comment by oscarcx123** [comment]
哇，第一次被人提issue，感谢支持~

其实吧，当时真没想到还会有其他人用，所以程序基本上糊出来就没改过了。最近在肝另一个项目，这个辅助有空应该也会继续搞的。

问题确定了，我最近懒得推图，没用辅助，就没发现辅助还是用的原来的老图标，而游戏换了新图标。我把图标替换下，然后发个新版本好了。如果还是出现明显很低的匹配率，那应该就是分辨率问题了，需要你自己进行截图然后替换素材文件。

我这边两个机子都测试通过了，有空我做个不同分辨率适配（1080p&1440p）。
