### ISSUE TITLE
跪求迷宫

### ISSUE THREAD

**Issue by leonyan18** [oscarcx123/afk-arena-tools#10]
迷宫耗时才是大头，迷宫自动，万家欢喜。
今天虽然做完了每日来用的，走了一遍感觉工会狩猎有点问题，走不到那个页面，然后就提示我打过了，是太快了？

**Comment by oscarcx123** [comment]
迷宫自动不好做，而且练度高的话容易翻车（比如遇到顶配的天神下凡队）。

每日任务我当时写完就没管了，现在感觉挺鸡肋的，还不如手动点几下，我都想直接砍掉这块了。你说功能有问题的话，那大概是莉莉丝又改了东西吧。

#6 我放了好久，就是看有没有人发现游戏内友情抽卡那里变了，但是两个多月过去了也没人提出来，估计本身就没人用。

所以应该是不会去修了，顶多屏蔽掉有问题的功能（或者全部砍掉），然后推图推塔倒是可以继续维护下，比如31-4多队推图，现在应该是会卡在“下一队”那里过不去的。这个项目最大的问题，就是用的2K分辨率素材，别人没有2K分辨率的设备就根本没法PR，我也没精力一个个地方测试，找出莉莉丝又改了啥。
