### ISSUE TITLE
1

### ISSUE THREAD

**Issue by chased9166** [oscarcx123/afk-arena-tools#12]

**Comment by oscarcx123** [comment]
一个ARPG不知道你想辅助啥。。。

- 想游戏内显示箱子，请找外挂。
- 想让弓箭角色打出加特林效果，请找鼠标宏，[不过也被官方定性为外挂](https://ngabbs.com/read.php?tid=23574575)。
- 想每日自动签到，请找[y1ndan / genshin-impact-helper](https://github.com/y1ndan/genshin-impact-helper)

我没外挂，也不支持和推荐用外挂，可能每日自动签到那个项目是唯一比较安全的吧。
