### ISSUE TITLE
可以提供一下升级界面的图片素材吗

### ISSUE THREAD

**Issue by gybuay** [oscarcx123/afk-arena-tools#4]
第一次研究这类代码，今天弄了个新号发现在升级的界面会卡住，我在模拟器720P的分辨率下自己截图放了进去img，用你的方法复制了一段match的等级提升界面的代码，然后debug输出看到匹配度才40%，没怎么用过opencv，想问一下你的素材是去哪里弄的，自己截图的效果好差。顺带一提，感谢你的开源，以后我也会写脚本了XD

**Comment by gybuay** [comment]
对了，我把core.py里面默认的 self.screen_height = 2560 self.screen_width = 1440改成720P也不行

**Comment by oscarcx123** [comment]
感谢大佬支持~

~~先确认一下，除了你加的功能之外，应该都是能用的吧？~~

刚刚写完回复，就意识到你说的这问题了。之前确实没想到这个场景，因为我的号已经170+级了，应该一会儿就能解决。

然后说第一个问题，因为我手机是2k屏，所以这个项目里头的图全都是基于2560*1440分辨率的。在GUI的杂项里头更改分辨率为1080p或720p后，程序会现场压图。这么做的原因是，高分辨率压图，肯定是能给低分辨率匹配上的；如果反过来，从720p去生成2k素材，应该是不靠谱的。当然我也有可能是错的，毕竟我就半桶水，如果有啥更好的方案很欢迎来讨论或者PR~

关于第二个问题，因为当初写这个辅助的时候，这个游戏还没出国服，也没发现有人在用，很多代码就是随便糊了能用就行，所以有些地方没有写清楚。实际上self.screen_height和self.screen_width这两个是不变的，更改分辨率的时候，调整的是self.scale_percentage。比如，从1440p调整到720p，实际操作是把self.scale_percentage从100降低到50，在main.py的change_resolution方法里头你可以看到具体实现。

至于开源嘛，我觉得反正都已经花时间写了，那不如顺便分享给大家用，互相交流学习才能进步啊，我自己也是从其它开源项目学到很多。

如果还要啥功能，可以随便提，在能力范围内我可以尽量做。

**Comment by gybuay** [comment]
是的，我猜想就是“从720p去生成2k素材，应该是不靠谱的”，所以我没有改self.scale_percentage，因为这个会压缩图片，我就直接把self.screen_height和self.screen_width改成720p了，这样就没有一个压缩的过程，但是用在我截图的素材上还是没有成功。。我也不知道为啥，并且我将screenshot和素材imshow看了一下，确实没有错。。

**Comment by oscarcx123** [comment]
我这边开了个小号，截图之后确认能识别到升级界面，我就顺手把这个问题解决了，更新了V1.0.7。

感觉你应该是截图的时候出了问题，因为根据你所说，是匹配率很低而不是匹配成功但是点不到。以win10自带的图片查看程序为例，你需要查看实际大小（View Actual Size）然后再截图。

不过如果你用720p素材的话，那就得全部替换了，估计也挺麻烦。我也是第一次写辅助，想不到什么好的提取素材的方法。

**Comment by gybuay** [comment]
ok~感谢
