### ISSUE TITLE
[Feature Request] Some thoughts on further development

### ISSUE THREAD

**Issue by sahuang** [oscarcx123/afk-arena-tools#5]
首先感谢作者推出了这么个工具，试了下还蛮好用的，想问下作者是否有如下计划：

1）v1.0.8 提到的**一键完成每日必做的任务**。有些任务可能比较复杂，比如竞技场，得找战力低的挑战；有些可能相对容易一些，比如挑战塔和主线（进入退出lls就算你完成了），再比如工会boss/收奖励这种。是否考虑先实现一些简单的任务支持？

2）挑战塔的时候如果阵容打不过，其实重试n次基本上也没用。但是多次实践表明，如果更换摆放角色的阵容（e.g. 狮子对位光盾比光盾对位光盾更好一些，可以打断光盾的防御buff），有时候能顺利过关。是否考虑在一键重试的板块增加自动换位的操作？

谢谢！

**Comment by oscarcx123** [comment]
感谢大佬支持，很抱歉来晚了，这个repo不知道为啥没有设置watch，刚刚才看到这个issue。

1）一键完成每日必做的任务本来早就该写了，但是当时觉得没什么人用，再加上afk偶尔会改版（比如悬赏任务现在游戏内可以直接一键），就一直拖到现在了。

每日必做就会涉及到个性化设置，到时候应该会有个配置文件。

大概整理了下日常做的任务，按道理没什么难点，应该可以全部支持：
* 挑战首领1次（20pts）
    * 进去出来就行
* 领取战利品2次（10pts）
    * 战役 > 箱子
* 赠送好友友情点1次（10pts）
    * 好友 > 一键领取和赠送
    * 潜在问题：领取点数不足20
* 快速挂机1次（10pts）
    * 战役 > 快速挂机
* 在月桂酒馆召唤英雄1次（20pts）
    * 这个一般抽友情，但是可能存在友情点数不够的问题
    * 忽略这个任务也是可以做到100pts
* 参加公会团队狩猎1次（10pts）
    * 领地 > 公会 > 公会狩猎
* 参加竞技场挑战1次（20pts）
    * 为确保胜利，肯定专挑软柿子捏
    * 方案一：直接打最下面的
    * 方案二：识别战力，挑最低的
* 接受3个悬赏任务（10pts）
    * 使用内置一键
    * 可以识别任务颜色和图标来判断悬赏类型，决定是否刷新
* 挑战王座之塔1次（10pts）
    * 挑战主塔，进去出来就行

装备升级就算了，这个任务应该没人做的。

迷宫不在任务里头，但是属于每日必做，这个个人感觉还是比较难处理，主要还是容易翻车，例如遇到+30骨王，+30绿剑，狮子，还有神魔队。

商铺自动买粉尘、瓜子、经验、紫碎，这个应该也好搞。

2）自动换位感觉有点鸡肋，因为其实可以直接在YouTube抄作业的，基本上主塔、种族塔、主线全都有不同流派的作业，总能找到合适的抄。比如有些作业是需要拼闪避的，那么就可以直接抄作业然后挂机直到通过。反正如果以后开发，那优先级肯定也比较低的啦。

最后，当然还是欢迎提想法、提意见、提PR~

我已经到28章了，在咸鱼状态，基本不怎么推图，很多东西未必能想到。

**Comment by sahuang** [comment]
谢谢回复 (不是大佬orz

感觉你写的基本上也囊括了大部分日常任务了，迷宫这种比较复杂，有些人可能想第一第二层多找战力高的怪刷buff，有些人可能就随便打打就过了，感觉还是手操稳妥些。

其他的都挺好，afk改版也不算大，我现在也就23章感觉有个tool肯定能方便不少www

至于用户的话其实可以贴吧或者群里宣传下啥的，我也比较咸鱼((

**Comment by oscarcx123** [comment]
~~哈哈哈本来想开工的，结果这几天沉迷团队本，大家都热情高涨，看来只能活动结束之后再搞了~~

~~这个issue我先不关，等搞定了才关掉~~

发布了V1.1.0版本，已经搞定了

**Comment by sahuang** [comment]
感谢,大佬nb!
