### ISSUE TITLE
公会狩猎和竞技场没有一键扫荡功能的没法走下去，进入死循环状态

### ISSUE THREAD

**Issue by kibozh** [oscarcx123/afk-arena-tools#6]
等级低玩家，例如本人86级，公会狩猎和竞技场没有一键扫荡功能，跑脚本发现没法走下去，进入死循环状态。求大佬解决一些这个问题，兼容低等级玩家~~~

**Comment by oscarcx123** [comment]
目前暂时不打算兼容120级以下玩家，否则下面这些东西需要单独处理。

| 条件     | 解锁功能       |
|----------|----------------|
| 120级/V6 | 公会boss扫荡   |
| 120级/V6 | 竞技场跳过战斗 |
| 120级/V6 | 一键悬赏栏     |

因为我的用户大多是老咸鱼，所以日常任务的逻辑默认就是游戏内全功能解锁的。不过如果还有其它人有这个需求，那我还是可以考虑去兼容的~

**Comment by zfang1995** [comment]
有需求的新玩家路过举个手

**Comment by oscarcx123** [comment]
~~就算兼容低等级玩家，优先级肯定也是很低的，毕竟这段时间也忙，现在已经进入维护状态了。~~

~~下面这些是短期可能做的功能：~~
* ~~最近新开的家具系统，就可以做个每日收礼物~~
* ~~自动挂机可以选择次数，这个现在很划算，都至少点到100钻的~~
* ~~通关之后给提示，并提供自动截图的选项~~

~~我反而觉得，现在重构是最重要的。最开始只是当一个自用的玩具项目来做的，确实没想到能有30 stars，所以内部代码结构一团糟，脚本和API的耦合度也很高，之后计划拆分。拆分之后，用户应该就能自己写需要的脚本了。~~

游戏弃坑了，详情可以看更新说明

**Comment by kibozh** [comment]
哈哈，自从提了这个issue，好久没看，也好久没用这个脚本了，本人现在已经148级了，感觉高等级之后的刷关卡主要看阵容和站位了，脚本作用也不是太大，就算用脚本刷了几百次刷过了，也领不到太多奖励，主要还是靠别的副本领奖励。作者一个人维护了这么久也真是难得。
