### ISSUE TITLE
自动推图功能无法自动进入下一章节

### ISSUE THREAD

**Issue by zfang1995** [oscarcx123/afk-arena-tools#7]

**Comment by oscarcx123** [comment]
没想到还能一个站位推到底，现在切换章节还是手动操作下吧🤣

当时糊代码的时候也没想太多，确实是不能自动进入下一章。做这个功能，也不太现实，因为每个章节的位置和图标都不一样，需要全部截一次，挺麻烦的。如果你有比较好的实现方法，欢迎讨论~
