### ISSUE TITLE
很好用，特意评论

### ISSUE THREAD

**Issue by ychai918** [oscarcx123/afk-arena-tools#8]
刚开始下载不知道怎么连接ADB，后来直接手机通过USB共享网络即可。
电脑上不需要下载雷电模拟器。

**Comment by oscarcx123** [comment]
感谢支持~

可能我readme写的不太好，我稍后修改下放上来，反正真机和模拟器都能用的。真机的话，进入开发者选项，打开USB调试就好。然后一般就是直接用线跟电脑连接，或者你有root的话，直接通过局域网连接也行。
