### ISSUE TITLE
无法运行

### ISSUE THREAD

**Issue by WilliamJiH** [oscarcx123/afk-arena-tools#9]
Windows10安装了pyQt5和open-cv，py版本3.8，启动闪一下cmd的框然后就没了。

**Comment by oscarcx123** [comment]
刚刚在Win10上试了下，八成是没安装requests吧，这个是上次更新加的，忘了在readme那里写。

以后入门级别的报错可以尝试自己解决，你这吓得我还以为是新版的包导致的兼容性问题。。。
